name: Run Python script
on:
 push:
  branches: [ main ]
 pull_request:
    branches: [ main ]


jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code      
     uses: actions/checkout@v2

   - name: Set up Python   
     uses: actions/setup-python@v2
     with:       
      python-version: 3.9  # Replace with the Python version you need


   - name: Setup secrets
     env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  
     run: |
        mkdir -p ~/.streamlit
        echo "[server]\nenableCORS = false\n\n[theme]\nprimaryColor='#F63366'\n\n
        [secrets]\nopenai = '$OPENAI_API_KEY'" > ~/.streamlit/config.toml

   - name: Execute Python script
     env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
     run: |
       python run ytubeqa.py
